import type { UnresolvedIssue, ChecklistItem, PartnerArtist } from './types';

export const seedIssues: UnresolvedIssue[] = [
  {
    id: 'ISS-001',
    title: '소셜 로그인 제공자 결정 (카카오/구글/애플)',
    category: '개발',
    priority: '긴급',
    owner: 'PM',
    status: '미결',
    blocker: 'OAuth 계약 미완료',
    dueDate: '2026-04-07',
    note: 'USER-001 요구사항. 카카오 비즈앱 승인 필요.',
    createdAt: '2026-03-15',
    updatedAt: '2026-03-28',
  },
  {
    id: 'ISS-002',
    title: '작품 이미지 CDN/스토리지 선정',
    category: '개발',
    priority: '긴급',
    owner: '개발팀',
    status: '진행 중',
    blocker: '',
    dueDate: '2026-04-03',
    note: 'AWS S3 + CloudFront vs Cloudflare R2 비교 중',
    createdAt: '2026-03-10',
    updatedAt: '2026-03-29',
  },
  {
    id: 'ISS-003',
    title: '저작권 보호 정책 법적 검토',
    category: '법무',
    priority: '높음',
    owner: '법무팀',
    status: '미결',
    blocker: '외부 법률 자문 대기',
    dueDate: '2026-04-10',
    note: '우클릭 방지 외 추가 보호 수단 검토. 이용약관 초안 필요.',
    createdAt: '2026-03-12',
    updatedAt: '2026-03-25',
  },
  {
    id: 'ISS-004',
    title: '런칭 이벤트 상품 예산 확정',
    category: '마케팅',
    priority: '높음',
    owner: '마케팅팀',
    status: '미결',
    blocker: '경영진 승인 대기',
    dueDate: '2026-04-05',
    note: 'MKT-001: 커피쿠폰 100건, MKT-002: 태블릿+스타일러스 10건',
    createdAt: '2026-03-18',
    updatedAt: '2026-03-27',
  },
  {
    id: 'ISS-005',
    title: '온보딩 플로우 디자인 확정',
    category: '디자인',
    priority: '보통',
    owner: '디자인팀',
    status: '진행 중',
    blocker: '',
    dueDate: '2026-04-08',
    note: '최초 로그인 시 작가명/닉네임 설정 온보딩 (USER-001)',
    createdAt: '2026-03-20',
    updatedAt: '2026-03-29',
  },
  {
    id: 'ISS-006',
    title: 'GA4 이벤트 추적 스펙 정의',
    category: '운영',
    priority: '보통',
    owner: 'PM',
    status: '미결',
    blocker: '',
    dueDate: '2026-04-12',
    note: '페이지뷰, 가입, 업로드, 이벤트 참여 등 핵심 이벤트 목록',
    createdAt: '2026-03-22',
    updatedAt: '2026-03-28',
  },
  {
    id: 'ISS-007',
    title: 'EXIF 차단 정밀도 테스트',
    category: '개발',
    priority: '보통',
    owner: '개발팀',
    status: '보류',
    blocker: 'ART-006 스펙 확정 필요',
    dueDate: '2026-04-15',
    note: '카메라 사진 차단 시 false positive 비율 측정 필요',
    createdAt: '2026-03-25',
    updatedAt: '2026-03-29',
  },
  {
    id: 'ISS-008',
    title: '파트너 작가 모집 채널 결정',
    category: '운영',
    priority: '높음',
    owner: '운영팀',
    status: '진행 중',
    blocker: '',
    dueDate: '2026-04-03',
    note: '문화센터, 동호회, SNS 채널 등 모집 경로 확정',
    createdAt: '2026-03-15',
    updatedAt: '2026-03-30',
  },
];

export const seedChecklist: ChecklistItem[] = [
  // QA
  { id: 'CL-001', title: '작품 업로드 E2E 테스트', description: '이미지 1~10장 업로드, 메타데이터 입력, 전시 등록 전체 플로우', category: 'QA', owner: 'QA팀', status: '시작 전', dueDate: '2026-04-18', checked: false },
  { id: 'CL-002', title: '프로필 편집 기능 테스트', description: '이름, 소개, 위치 변경 후 저장/표시 확인', category: 'QA', owner: 'QA팀', status: '시작 전', dueDate: '2026-04-18', checked: false },
  { id: 'CL-003', title: '좋아요/저장 기능 테스트', description: '로그인/비로그인 상태에서 좋아요, 저장 토글 확인', category: 'QA', owner: 'QA팀', status: '시작 전', dueDate: '2026-04-18', checked: false },
  { id: 'CL-004', title: '반응형 레이아웃 검증', description: 'PC, 태블릿, 모바일 3종 해상도 테스트', category: 'QA', owner: 'QA팀', status: '시작 전', dueDate: '2026-04-20', checked: false },
  { id: 'CL-005', title: '이미지 로딩 성능 (3초 이내)', description: '메인/상세 페이지 이미지 3초 내 로드 확인', category: 'QA', owner: '개발팀', status: '시작 전', dueDate: '2026-04-20', checked: false },
  // Legal
  { id: 'CL-006', title: '이용약관 작성 및 게시', description: '서비스 이용약관 법적 검토 완료 후 게시', category: '법무', owner: '법무팀', status: '시작 전', dueDate: '2026-04-15', checked: false },
  { id: 'CL-007', title: '개인정보처리방침 게시', description: 'GDPR/PIPA 준수 개인정보처리방침', category: '법무', owner: '법무팀', status: '시작 전', dueDate: '2026-04-15', checked: false },
  { id: 'CL-008', title: '저작권 보호 고지문 게시', description: '작품 도용 시 법적 조치 고지', category: '법무', owner: '법무팀', status: '시작 전', dueDate: '2026-04-15', checked: false },
  // Content
  { id: 'CL-009', title: '초기 작품 100점 이상 확보', description: '파트너 작가 작품으로 서비스 오픈 전 콘텐츠 채움', category: '콘텐츠', owner: '운영팀', status: '진행 중', dueDate: '2026-04-25', checked: false },
  { id: 'CL-010', title: '이벤트 배너 디자인 완료', description: 'MKT-001, MKT-002 이벤트 배너 2종', category: '콘텐츠', owner: '디자인팀', status: '진행 중', dueDate: '2026-04-10', checked: false },
  { id: 'CL-011', title: 'Artier 소개 페이지 콘텐츠', description: '서비스 소개 및 비전 텍스트', category: '콘텐츠', owner: 'PM', status: '시작 전', dueDate: '2026-04-20', checked: false },
  // Operations
  { id: 'CL-012', title: '모니터링/알림 셋업', description: '에러 트래킹(Sentry 등) 및 가동 모니터링', category: '운영', owner: '개발팀', status: '시작 전', dueDate: '2026-04-22', checked: false },
  { id: 'CL-013', title: '콘텐츠 검수 프로세스 수립', description: 'PM 콘텐츠 검수 가이드라인 및 위반 대응 절차', category: '운영', owner: 'PM', status: '시작 전', dueDate: '2026-04-18', checked: false },
  { id: 'CL-014', title: '고객 문의 채널 개설', description: '이메일 또는 채팅 기반 문의 채널', category: '운영', owner: '운영팀', status: '시작 전', dueDate: '2026-04-25', checked: false },
  // Marketing
  { id: 'CL-015', title: 'SNS 계정 생성 및 사전 홍보', description: '인스타그램, 트위터 공식 계정 운영 시작', category: '마케팅', owner: '마케팅팀', status: '진행 중', dueDate: '2026-04-10', checked: false },
  { id: 'CL-016', title: '런칭 보도자료 작성', description: '미디어 배포용 보도자료', category: '마케팅', owner: '마케팅팀', status: '시작 전', dueDate: '2026-04-22', checked: false },
  { id: 'CL-017', title: 'CBT 참여자 모집 (20명)', description: '4월 3주차 비공개 베타 테스트 참여자', category: '마케팅', owner: '마케팅팀', status: '시작 전', dueDate: '2026-04-14', checked: false },
];

export const seedPartnerArtists: PartnerArtist[] = [
  { id: 'PA-001', name: '카테', email: 'cho.gayoung@email.com', stage: '활성', contactStatus: '정기 연락', submissionStatus: '제출 완료', worksCount: 7, notes: '디지털 페인팅 전문. 초기 콘텐츠 핵심 작가.', monthlyRoutine: '월 2회 작품 업로드 약속', joinedAt: '2026-03-01', lastContactAt: '2026-03-28' },
  { id: 'PA-002', name: '김영자', email: 'kim.youngja@email.com', stage: '활성', contactStatus: '정기 연락', submissionStatus: '제출 완료', worksCount: 5, notes: '30년 경력 동양화 작가. 문화센터 강사.', monthlyRoutine: '월 1회 작품 + 수강생 작품 대리 업로드', joinedAt: '2026-03-01', lastContactAt: '2026-03-25' },
  { id: 'PA-003', name: '정호아트', email: 'park.jh@email.com', stage: '활성', contactStatus: '정기 연락', submissionStatus: '제출 완료', worksCount: 4, notes: '전통/현대 미술 경계 작업', monthlyRoutine: '월 2회 업로드', joinedAt: '2026-03-05', lastContactAt: '2026-03-27' },
  { id: 'PA-004', name: '실과바늘', email: 'choi.mk@email.com', stage: '온보딩 중', contactStatus: '초기 안내 완료', submissionStatus: '미제출', worksCount: 0, notes: '섬유/도자기 공예. 작품 촬영 지원 필요.', monthlyRoutine: '미정', joinedAt: '2026-03-20', lastContactAt: '2026-03-22' },
  { id: 'PA-005', name: '은수워터컬러', email: 'jung.es@email.com', stage: '활성', contactStatus: '정기 연락', submissionStatus: '제출 완료', worksCount: 6, notes: '제품 디자이너 겸 수채화 작가', monthlyRoutine: '월 3회 업로드', joinedAt: '2026-03-03', lastContactAt: '2026-03-29' },
  { id: 'PA-006', name: '홍순덕', email: 'hong.sd@email.com', stage: '연락 완료', contactStatus: '관심 표명', submissionStatus: '미제출', worksCount: 0, notes: '전통 자수/섬유 예술 25년. 디지털화 지원 필요.', monthlyRoutine: '미정', joinedAt: '2026-03-18', lastContactAt: '2026-03-20' },
  { id: 'PA-007', name: '내면의풍경', email: 'seo.kh@email.com', stage: '활성', contactStatus: '정기 연락', submissionStatus: '제출 완료', worksCount: 5, notes: '추상화 전문. SNS 팔로워 많음.', monthlyRoutine: '월 2회 업로드', joinedAt: '2026-03-02', lastContactAt: '2026-03-30' },
  { id: 'PA-008', name: '나무결공방', email: 'yoon.ts@email.com', stage: '온보딩 중', contactStatus: '가이드 전달', submissionStatus: '검토 중', worksCount: 2, notes: '목공예/가구 디자인. 작품 사진 품질 좋음.', monthlyRoutine: '월 1회 업로드 예정', joinedAt: '2026-03-15', lastContactAt: '2026-03-26' },
  { id: 'PA-009', name: '강미란', email: 'kang.mr@email.com', stage: '활성', contactStatus: '정기 연락', submissionStatus: '제출 완료', worksCount: 4, notes: '도자 공예. 작품 + 제작 과정 타임랩스 제공 가능.', monthlyRoutine: '월 2회 업로드', joinedAt: '2026-03-04', lastContactAt: '2026-03-28' },
  { id: 'PA-010', name: '이종환', email: 'lee.jh@email.com', stage: '후보', contactStatus: '1차 연락 시도', submissionStatus: '미제출', worksCount: 0, notes: '수채화 35년 경력. 디지털 전환 관심. SNS DM으로 접근.', monthlyRoutine: '미정', joinedAt: '2026-03-28', lastContactAt: '2026-03-28' },
  { id: 'PA-011', name: '소소한하루', email: 'song.mh@email.com', stage: '연락 완료', contactStatus: '참여 의사 확인 중', submissionStatus: '미제출', worksCount: 0, notes: '일상 디지털 기록 작가. 문화센터 연계 가능.', monthlyRoutine: '미정', joinedAt: '2026-03-22', lastContactAt: '2026-03-24' },
  { id: 'PA-012', name: '정림수채화', email: 'oh.jl@email.com', stage: '활성', contactStatus: '정기 연락', submissionStatus: '제출 완료', worksCount: 8, notes: '40년 화가. 디지털 수채 작업. 핵심 파트너.', monthlyRoutine: '월 3회 업로드', joinedAt: '2026-03-01', lastContactAt: '2026-03-30' },
];
